"""Regenerate the generated docs — `SCAFFOLD.md` and the shelf indexes — from the index.

All are built from the index, not the worktree: at pre-commit time the index
is the commit, so a file staged for addition appears and a file staged for
deletion is gone, whatever else is lying around unstaged. All quote a line the
source file already had — a module's first docstring line, a note's first
paragraph — so no document can drift from what it indexes: rewriting that
line rewrites this document, and a directory that never says what it is for
shows up here with nothing after its name.

`--check` reports staleness instead of writing, for a caller that wants to fail
rather than fix.
"""

from __future__ import annotations

import argparse
import ast
import re
import subprocess
import sys
from pathlib import PurePosixPath
from typing import NamedTuple

DOCS = "docs/"
DOC_PATH = "docs/SCAFFOLD.md"
HEADER = "<!-- Generated by scripts/doc_index.py. Do not edit; rerun the tool. -->"
TITLE = "# SCAFFOLD — where things live"

SOLUTIONS_DIR = "docs/solutions/"
SOLUTIONS_DOC = "docs/solutions/INDEX.md"
SOLUTIONS_TITLE = "# SOLUTIONS — what not to reinvent"
SOLUTIONS_PREAMBLE = """\
Derived: each line is its solution's frontmatter, so that file is the home
and this index cannot drift from it. Before building a mechanism, scan this
list — if the want is here, the repo already has an answer."""


class Shelf(NamedTuple):
    """A directory of front-mattered notes, and the index generated from it.

    Every shelf is read and rendered the same way; what differs is only where
    the notes live, where their index lands, and what the page says it is for.
    """

    directory: str  # under docs/, so a link from the index is the tail of it
    doc_path: str
    title: str
    preamble: str
    tally: str  # takes the number of notes that made it onto the shelf
    #: A shelf that names a second section splits `status: unsettled` notes
    #: into it, under its own heading and tally. A shelf that leaves these
    #: empty renders one list and ignores `status` entirely.
    pending_title: str = ""
    pending_preamble: str = ""
    pending_tally: str = ""


SHELVES = [
    Shelf(
        directory="docs/adr/",
        doc_path="docs/ADR.md",
        title="# ADR — what is settled",
        preamble="""\
Derived: each line is its ADR's first paragraph, so that file is the home and
this index cannot drift from it. The shelf an ADR sits on is `group` and its
order along that shelf is `position`, both placement only — an ADR that drops
its group leaves this index while keeping its number and its file.""",
        tally="*{count} settled.*",
    ),
    Shelf(
        directory="docs/vocab/",
        doc_path="docs/VOCAB.md",
        title="# VOCAB — what the words mean",
        preamble="""\
Derived: each line is its term's `gloss`, so that file is the home and this
index cannot drift from it. A gloss is capped and names no code, which is what
keeps this page scannable and keeps a rename out of it — the entry's own
`## Where it lives` is where code goes, and `checks/vocab.py` holds both to it.
The shelf a term sits on is `group` and its order along that shelf is
`position`, both placement only — a term that drops its group leaves this index
while keeping its file. A term the tree has not agreed on is listed apart,
below.""",
        tally="*{count} defined.*",
        pending_title="## Unsettled",
        pending_preamble="""\
A term is here because the tree does not agree on it yet: several live senses
at once, or a definition the code has walked away from. Listed rather than
left out, because the disagreement is what is being raised and a word nobody
wrote down is a word nobody argues with. `status: unsettled` in the
frontmatter is what puts a term here; deleting that line is what settles
it.""",
        pending_tally="*{count} contested.*",
    ),
]


def _git(*args: str) -> bytes:
    return subprocess.run(
        ["git", *args], check=True, stdout=subprocess.PIPE
    ).stdout


def repo_root() -> PurePosixPath:
    return PurePosixPath(_git("rev-parse", "--show-toplevel").decode().strip())


def tracked_paths() -> list[str]:
    out = _git("ls-files", "-z").decode("utf-8")
    return sorted(p for p in out.split("\0") if p)


def read_index(paths: list[str]) -> dict[str, bytes]:
    """The staged bytes of every path, in one `git cat-file` pass."""
    if not paths:
        return {}
    query = "".join(f":{p}\n" for p in paths).encode("utf-8")
    proc = subprocess.run(
        ["git", "cat-file", "--batch"],
        input=query,
        check=True,
        stdout=subprocess.PIPE,
    )
    blobs: dict[str, bytes] = {}
    buf = proc.stdout
    pos = 0
    for path in paths:
        eol = buf.index(b"\n", pos)
        header = buf[pos:eol].decode("utf-8")
        if header.endswith(("missing", "ambiguous")):
            pos = eol + 1
            continue
        size = int(header.rsplit(" ", 1)[1])
        blobs[path] = buf[eol + 1 : eol + 1 + size]
        pos = eol + 1 + size + 1  # trailing newline cat-file adds
    return blobs


def gloss(source: bytes) -> str:
    """The first line of a module's docstring, or nothing if it has none."""
    try:
        doc = ast.get_docstring(ast.parse(source.decode("utf-8")))
    except (SyntaxError, UnicodeDecodeError):
        return ""
    if not doc:
        return ""
    return doc.strip().splitlines()[0].strip()


FOLDER = "📁"
FILE = "📄"


def tree(paths: list[str]) -> dict:
    """Nest flat paths into `{name: subtree}` dicts, files mapping to `None`."""
    root: dict = {}
    for path in paths:
        node = root
        parts = PurePosixPath(path).parts
        for part in parts[:-1]:
            node = node.setdefault(part, {})
        node[parts[-1]] = None
    return root


def render(paths: list[str], blobs: dict[str, bytes]) -> str:
    glosses = {
        p: gloss(blobs[p]) for p in paths if p.endswith(".py") and p in blobs
    }

    def entries(node: dict, prefix: str, depth: int) -> list[str]:
        """One list item per child, directories first, their contents beneath.

        A directory speaks with its `__init__.py`'s gloss, and that file then
        keeps quiet: the line is already on the page, one indent shallower.
        """
        lines = []
        indent = "  " * depth
        dirs = sorted(k for k, v in node.items() if v is not None)
        files = sorted(k for k, v in node.items() if v is None)
        for name in dirs:
            subtree = node[name]
            init = f"{prefix}{name}/__init__.py"
            line = f"{indent}- {FOLDER} `{name}/`"
            if glosses.get(init):
                line += f" — {glosses[init]}"
            sub_files = [k for k, v in subtree.items() if v is None]
            sub_dirs = [k for k, v in subtree.items() if v is not None]
            if (not sub_dirs
                    and len(sub_files) > 5
                    and not any(f.endswith(".py") for f in sub_files)):
                line += f" ({len(sub_files)} files)"
                lines.append(line)
                continue
            lines.append(line)
            lines += entries(subtree, f"{prefix}{name}/", depth + 1)
        for name in files:
            path = f"{prefix}{name}"
            if name == "__init__.py" and glosses.get(path):
                continue  # already said, as the directory's own line
            line = f"{indent}- {FILE} `{name}`"
            if glosses.get(path):
                line += f" — {glosses[path]}"
            lines.append(line)
        return lines

    return "\n".join([HEADER, "", TITLE, "", *entries(tree(paths), "", 0), ""])


def front_matter(source: bytes) -> tuple[dict[str, str], str]:
    """A note's `key: value` header, and the paragraph that follows it.

    Hand-parsed rather than run through a YAML reader: the header is flat
    scalars, and the repo has no YAML dependency to add for four of them.
    """
    text = source.decode("utf-8").replace("\r\n", "\n")
    if not text.startswith("---\n"):
        return {}, ""
    header, _, body = text[4:].partition("\n---\n")
    fields = {}
    for line in header.splitlines():
        key, sep, value = line.partition(":")
        if sep:
            fields[key.strip()] = value.strip().strip("\"'")
    paragraph = " ".join(
        line.strip() for line in body.strip().split("\n\n")[0].splitlines()
    )
    return fields, paragraph


def natural(text: str) -> list:
    """Sort key that reads digit runs as numbers, so `Layer 9` precedes `10`."""
    return [
        int(part) if part.isdigit() else part.casefold()
        for part in re.split(r"(\d+)", text)
    ]


def render_shelf(shelf: Shelf, paths: list[str], blobs: dict[str, bytes]) -> str:
    """One shelf's notes, grouped by `group`, in SCAFFOLD's indented list.

    A note with no `group` is placed nowhere and so appears nowhere; that is
    the one way off an index, and it leaves the file itself untouched.
    `position` orders a group from the front, and one that omits it sits after
    everything that named a place, in filename order.

    A shelf that names a second section reads `status` as well: `unsettled`
    sends a note to that section, everything else to the first. The two are
    rendered the same way and tallied apart, so a term can be recorded before
    the tree agrees on it without being read as agreed.
    """
    groups: dict[str, list[tuple[list, bool, str, str, str, str]]] = {}
    pending: dict[str, list[tuple[list, bool, str, str, str, str]]] = {}
    for path in sorted(paths):
        name = path[len(shelf.directory) :]
        if (
            not path.startswith(shelf.directory)
            or "/" in name
            or name.startswith("_")
        ):
            continue
        fields, paragraph = front_matter(blobs.get(path, b""))
        if not fields.get("group"):
            continue
        # A shelf whose notes carry a `gloss` speaks with it; one whose notes
        # do not falls back to the paragraph. The gloss is a line written to be
        # quoted here, and it is capped where the paragraph is not.
        paragraph = fields.get("gloss") or paragraph
        position = fields.get("position", "")
        link = f"{shelf.directory[len(DOCS):]}{name}"
        unsettled = (
            bool(shelf.pending_title)
            and fields.get("status", "") == "unsettled"
        )
        shelved = pending if unsettled else groups
        shelved.setdefault(fields["group"], []).append(
            (natural(position), not position, name, fields.get("title", name),
             link, paragraph)
        )

    def section(
        shelved: dict[str, list[tuple[list, bool, str, str, str, str]]],
        tally: str,
    ) -> list[str]:
        lines = []
        for group in sorted(shelved, key=natural):
            lines.append(f"- {FOLDER} `{group}`")
            for _, _, _, title, link, paragraph in sorted(
                shelved[group], key=lambda entry: (entry[1], entry[0], entry[2])
            ):
                line = f"  - {FILE} [{title}]({link})"
                if paragraph:
                    line += f" — {paragraph}"
                lines.append(line)
        count = sum(len(group) for group in shelved.values())
        return [*lines, "", tally.format(count=count)]

    body = section(groups, shelf.tally)
    if pending:
        body += ["", shelf.pending_title, "", shelf.pending_preamble, ""]
        body += section(pending, shelf.pending_tally)
    return "\n".join(
        [HEADER, "", shelf.title, "", shelf.preamble, "", *body, ""]
    )


def render_solutions(paths: list[str], blobs: dict[str, bytes]) -> str:
    entries = []
    for path in sorted(paths):
        name = path[len(SOLUTIONS_DIR):]
        if (
            not path.startswith(SOLUTIONS_DIR)
            or "/" in name
            or name.startswith("_")
            or name == "INDEX.md"
        ):
            continue
        fields, _ = front_matter(blobs.get(path, b""))
        want = fields.get("want")
        answer = fields.get("answer")
        if not want or not answer:
            continue
        entries.append((want.lower(), want, answer))
    entries.sort()
    lines = [f"- **{want}** → {answer}" for _, want, answer in entries]
    tally = f"*{len(lines)} solved.*"
    return "\n".join(
        [HEADER, "", SOLUTIONS_TITLE, "", SOLUTIONS_PREAMBLE, "", *lines, "",
         tally, ""]
    )


def write(root: PurePosixPath, doc_path: str, text: str) -> bool:
    """Write the map, keeping whatever line endings the file already has.

    Returns whether anything changed. The endings are read off the file's own
    bytes rather than assumed: `core.autocrlf` is on, so a checkout leaves CRLF
    on disk, and rewriting it as LF would show every line as modified in a diff
    that only ever normalises back to what git already had.
    """
    target = root / doc_path
    try:
        old = open(target, "rb").read()
    except FileNotFoundError:
        old = b""
    newline = b"\r\n" if b"\r\n" in old else b"\n"
    new = newline.join(text.encode("utf-8").split(b"\n"))
    if new == old:
        return False
    with open(target, "wb") as fh:
        fh.write(new)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the map is stale, instead of rewriting it",
    )
    parser.add_argument("--quiet", action="store_true", help="say nothing")
    args = parser.parse_args()

    root = repo_root()
    paths = tracked_paths()
    blobs = read_index(paths)
    docs = [
        (DOC_PATH, render(paths, blobs)),
        *(
            (shelf.doc_path, render_shelf(shelf, paths, blobs))
            for shelf in SHELVES
        ),
        (SOLUTIONS_DOC, render_solutions(paths, blobs)),
    ]

    if args.check:
        stale = []
        for doc_path, text in docs:
            try:
                current = open(root / doc_path, "rb").read()
            except FileNotFoundError:
                current = b""
            if current.replace(b"\r\n", b"\n") != text.encode("utf-8"):
                stale.append(doc_path)
        if stale and not args.quiet:
            names = ", ".join(stale)
            print(f"{names} stale; run `uv run python scripts/doc_index.py`")
        return 1 if stale else 0

    for doc_path, text in docs:
        if write(root, doc_path, text) and not args.quiet:
            print(f"{doc_path} rewritten")
    return 0


if __name__ == "__main__":
    sys.exit(main())
