"""Regenerate the generated docs — `SCAFFOLD.md`, `ADR-SUMMARY.md` — from the index.

Both are built from the index, not the worktree: at pre-commit time the index
is the commit, so a file staged for addition appears and a file staged for
deletion is gone, whatever else is lying around unstaged. Both quote a line the
source file already had — a module's first docstring line, an ADR's first
paragraph — so neither document can drift from what it indexes: rewriting that
line rewrites this document, and a directory that never says what it is for
shows up here with nothing after its name.

`--check` reports staleness instead of writing, for a caller that wants to fail
rather than fix.
"""

from __future__ import annotations

import argparse
import ast
import re
import subprocess
import sys
from pathlib import PurePosixPath

DOC_PATH = "docs/SCAFFOLD.md"
HEADER = "<!-- Generated by scripts/doc_index.py. Do not edit; rerun the tool. -->"
TITLE = "# SCAFFOLD — where things live"

ADR_DIR = "docs/adr/"
ADR_DOC_PATH = "docs/ADR-SUMMARY.md"
ADR_TITLE = "# ADR-SUMMARY — what is settled"
ADR_PREAMBLE = """\
Derived: each line is its ADR's first paragraph, so that file is the home and
this index cannot drift from it. The shelf an ADR sits on is `group` and its
order along that shelf is `position`, both placement only — an ADR that drops
its group leaves this index while keeping its number and its file."""


def _git(*args: str) -> bytes:
    return subprocess.run(
        ["git", *args], check=True, stdout=subprocess.PIPE
    ).stdout


def repo_root() -> PurePosixPath:
    return PurePosixPath(_git("rev-parse", "--show-toplevel").decode().strip())


def tracked_paths() -> list[str]:
    out = _git("ls-files", "-z").decode("utf-8")
    return sorted(p for p in out.split("\0") if p)


def read_index(paths: list[str]) -> dict[str, bytes]:
    """The staged bytes of every path, in one `git cat-file` pass."""
    if not paths:
        return {}
    query = "".join(f":{p}\n" for p in paths).encode("utf-8")
    proc = subprocess.run(
        ["git", "cat-file", "--batch"],
        input=query,
        check=True,
        stdout=subprocess.PIPE,
    )
    blobs: dict[str, bytes] = {}
    buf = proc.stdout
    pos = 0
    for path in paths:
        eol = buf.index(b"\n", pos)
        header = buf[pos:eol].decode("utf-8")
        if header.endswith(("missing", "ambiguous")):
            pos = eol + 1
            continue
        size = int(header.rsplit(" ", 1)[1])
        blobs[path] = buf[eol + 1 : eol + 1 + size]
        pos = eol + 1 + size + 1  # trailing newline cat-file adds
    return blobs


def gloss(source: bytes) -> str:
    """The first line of a module's docstring, or nothing if it has none."""
    try:
        doc = ast.get_docstring(ast.parse(source.decode("utf-8")))
    except (SyntaxError, UnicodeDecodeError):
        return ""
    if not doc:
        return ""
    return doc.strip().splitlines()[0].strip()


FOLDER = "📁"
FILE = "📄"


def tree(paths: list[str]) -> dict:
    """Nest flat paths into `{name: subtree}` dicts, files mapping to `None`."""
    root: dict = {}
    for path in paths:
        node = root
        parts = PurePosixPath(path).parts
        for part in parts[:-1]:
            node = node.setdefault(part, {})
        node[parts[-1]] = None
    return root


def render(paths: list[str], blobs: dict[str, bytes]) -> str:
    glosses = {
        p: gloss(blobs[p]) for p in paths if p.endswith(".py") and p in blobs
    }

    def entries(node: dict, prefix: str, depth: int) -> list[str]:
        """One list item per child, directories first, their contents beneath.

        A directory speaks with its `__init__.py`'s gloss, and that file then
        keeps quiet: the line is already on the page, one indent shallower.
        """
        lines = []
        indent = "  " * depth
        dirs = sorted(k for k, v in node.items() if v is not None)
        files = sorted(k for k, v in node.items() if v is None)
        for name in dirs:
            init = f"{prefix}{name}/__init__.py"
            line = f"{indent}- {FOLDER} `{name}/`"
            if glosses.get(init):
                line += f" — {glosses[init]}"
            lines.append(line)
            lines += entries(node[name], f"{prefix}{name}/", depth + 1)
        for name in files:
            path = f"{prefix}{name}"
            if name == "__init__.py" and glosses.get(path):
                continue  # already said, as the directory's own line
            line = f"{indent}- {FILE} `{name}`"
            if glosses.get(path):
                line += f" — {glosses[path]}"
            lines.append(line)
        return lines

    return "\n".join([HEADER, "", TITLE, "", *entries(tree(paths), "", 0), ""])


def front_matter(source: bytes) -> tuple[dict[str, str], str]:
    """An ADR's `key: value` header, and the paragraph that follows it.

    Hand-parsed rather than run through a YAML reader: the header is flat
    scalars, and the repo has no YAML dependency to add for four of them.
    """
    text = source.decode("utf-8").replace("\r\n", "\n")
    if not text.startswith("---\n"):
        return {}, ""
    header, _, body = text[4:].partition("\n---\n")
    fields = {}
    for line in header.splitlines():
        key, sep, value = line.partition(":")
        if sep:
            fields[key.strip()] = value.strip().strip("\"'")
    paragraph = " ".join(
        line.strip() for line in body.strip().split("\n\n")[0].splitlines()
    )
    return fields, paragraph


def natural(text: str) -> list:
    """Sort key that reads digit runs as numbers, so `Layer 9` precedes `10`."""
    return [
        int(part) if part.isdigit() else part.casefold()
        for part in re.split(r"(\d+)", text)
    ]


def render_adrs(paths: list[str], blobs: dict[str, bytes]) -> str:
    """The shelf of ADRs, grouped by `group`, in SCAFFOLD's indented list.

    An ADR with no `group` is placed nowhere and so appears nowhere; that is
    the one way off this index, and it leaves the file itself untouched.
    `position` orders a group from the front, and one that omits it sits after
    everything that named a place, in filename order.
    """
    shelf: dict[str, list[tuple[list, bool, str, str, str, str]]] = {}
    for path in sorted(paths):
        name = path[len(ADR_DIR) :]
        if not path.startswith(ADR_DIR) or "/" in name or name.startswith("_"):
            continue
        fields, paragraph = front_matter(blobs.get(path, b""))
        if not fields.get("group"):
            continue
        position = fields.get("position", "")
        shelf.setdefault(fields["group"], []).append(
            (natural(position), not position, name, fields.get("title", name),
             f"adr/{name}", paragraph)
        )

    lines = []
    for group in sorted(shelf, key=natural):
        lines.append(f"- {FOLDER} `{group}`")
        for _, _, _, title, link, paragraph in sorted(
            shelf[group], key=lambda entry: (entry[1], entry[0], entry[2])
        ):
            line = f"  - {FILE} [{title}]({link})"
            if paragraph:
                line += f" — {paragraph}"
            lines.append(line)

    count = sum(len(group) for group in shelf.values())
    tally = f"*{count} settled.*"
    return "\n".join(
        [HEADER, "", ADR_TITLE, "", ADR_PREAMBLE, "", *lines, "", tally, ""]
    )


def write(root: PurePosixPath, doc_path: str, text: str) -> bool:
    """Write the map, keeping whatever line endings the file already has.

    Returns whether anything changed. The endings are read off the file's own
    bytes rather than assumed: `core.autocrlf` is on, so a checkout leaves CRLF
    on disk, and rewriting it as LF would show every line as modified in a diff
    that only ever normalises back to what git already had.
    """
    target = root / doc_path
    try:
        old = open(target, "rb").read()
    except FileNotFoundError:
        old = b""
    newline = b"\r\n" if b"\r\n" in old else b"\n"
    new = newline.join(text.encode("utf-8").split(b"\n"))
    if new == old:
        return False
    with open(target, "wb") as fh:
        fh.write(new)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the map is stale, instead of rewriting it",
    )
    parser.add_argument("--quiet", action="store_true", help="say nothing")
    args = parser.parse_args()

    root = repo_root()
    paths = tracked_paths()
    blobs = read_index(paths)
    docs = [
        (DOC_PATH, render(paths, blobs)),
        (ADR_DOC_PATH, render_adrs(paths, blobs)),
    ]

    if args.check:
        stale = []
        for doc_path, text in docs:
            try:
                current = open(root / doc_path, "rb").read()
            except FileNotFoundError:
                current = b""
            if current.replace(b"\r\n", b"\n") != text.encode("utf-8"):
                stale.append(doc_path)
        if stale and not args.quiet:
            names = ", ".join(stale)
            print(f"{names} stale; run `uv run python scripts/doc_index.py`")
        return 1 if stale else 0

    for doc_path, text in docs:
        if write(root, doc_path, text) and not args.quiet:
            print(f"{doc_path} rewritten")
    return 0


if __name__ == "__main__":
    sys.exit(main())
