"""Regenerate `docs/SCAFFOLD.md` from the tree git is about to commit.

The map is built from the index, not the worktree: at pre-commit time the index
is the commit, so a file staged for addition appears and a file staged for
deletion is gone, whatever else is lying around unstaged. Glosses are the first
line of each module's docstring, so the map cannot drift from the modules —
moving a file or rewriting its opening line rewrites this document, and a
directory that never says what it is for shows up here with nothing after its
name.

`--check` reports staleness instead of writing, for a caller that wants to fail
rather than fix.
"""

from __future__ import annotations

import argparse
import ast
import subprocess
import sys
from pathlib import PurePosixPath

DOC_PATH = "docs/SCAFFOLD.md"
HEADER = "<!-- Generated by scripts/doc_index.py. Do not edit; rerun the tool. -->"
TITLE = "# SCAFFOLD — where things live"


def _git(*args: str) -> bytes:
    return subprocess.run(
        ["git", *args], check=True, stdout=subprocess.PIPE
    ).stdout


def repo_root() -> PurePosixPath:
    return PurePosixPath(_git("rev-parse", "--show-toplevel").decode().strip())


def tracked_paths() -> list[str]:
    out = _git("ls-files", "-z").decode("utf-8")
    return sorted(p for p in out.split("\0") if p)


def read_index(paths: list[str]) -> dict[str, bytes]:
    """The staged bytes of every path, in one `git cat-file` pass."""
    if not paths:
        return {}
    query = "".join(f":{p}\n" for p in paths).encode("utf-8")
    proc = subprocess.run(
        ["git", "cat-file", "--batch"],
        input=query,
        check=True,
        stdout=subprocess.PIPE,
    )
    blobs: dict[str, bytes] = {}
    buf = proc.stdout
    pos = 0
    for path in paths:
        eol = buf.index(b"\n", pos)
        header = buf[pos:eol].decode("utf-8")
        if header.endswith(("missing", "ambiguous")):
            pos = eol + 1
            continue
        size = int(header.rsplit(" ", 1)[1])
        blobs[path] = buf[eol + 1 : eol + 1 + size]
        pos = eol + 1 + size + 1  # trailing newline cat-file adds
    return blobs


def gloss(source: bytes) -> str:
    """The first line of a module's docstring, or nothing if it has none."""
    try:
        doc = ast.get_docstring(ast.parse(source.decode("utf-8")))
    except (SyntaxError, UnicodeDecodeError):
        return ""
    if not doc:
        return ""
    return doc.strip().splitlines()[0].strip()


FOLDER = "📁"
FILE = "📄"


def tree(paths: list[str]) -> dict:
    """Nest flat paths into `{name: subtree}` dicts, files mapping to `None`."""
    root: dict = {}
    for path in paths:
        node = root
        parts = PurePosixPath(path).parts
        for part in parts[:-1]:
            node = node.setdefault(part, {})
        node[parts[-1]] = None
    return root


def render(paths: list[str], blobs: dict[str, bytes]) -> str:
    glosses = {
        p: gloss(blobs[p]) for p in paths if p.endswith(".py") and p in blobs
    }

    def entries(node: dict, prefix: str, depth: int) -> list[str]:
        """One list item per child, directories first, their contents beneath.

        A directory speaks with its `__init__.py`'s gloss, and that file then
        keeps quiet: the line is already on the page, one indent shallower.
        """
        lines = []
        indent = "  " * depth
        dirs = sorted(k for k, v in node.items() if v is not None)
        files = sorted(k for k, v in node.items() if v is None)
        for name in dirs:
            init = f"{prefix}{name}/__init__.py"
            line = f"{indent}- {FOLDER} `{name}/`"
            if glosses.get(init):
                line += f" — {glosses[init]}"
            lines.append(line)
            lines += entries(node[name], f"{prefix}{name}/", depth + 1)
        for name in files:
            path = f"{prefix}{name}"
            if name == "__init__.py" and glosses.get(path):
                continue  # already said, as the directory's own line
            line = f"{indent}- {FILE} `{name}`"
            if glosses.get(path):
                line += f" — {glosses[path]}"
            lines.append(line)
        return lines

    return "\n".join([HEADER, "", TITLE, "", *entries(tree(paths), "", 0), ""])


def write(root: PurePosixPath, text: str) -> bool:
    """Write the map, keeping whatever line endings the file already has.

    Returns whether anything changed. The endings are read off the file's own
    bytes rather than assumed: `core.autocrlf` is on, so a checkout leaves CRLF
    on disk, and rewriting it as LF would show every line as modified in a diff
    that only ever normalises back to what git already had.
    """
    target = root / DOC_PATH
    try:
        old = open(target, "rb").read()
    except FileNotFoundError:
        old = b""
    newline = b"\r\n" if b"\r\n" in old else b"\n"
    new = newline.join(text.encode("utf-8").split(b"\n"))
    if new == old:
        return False
    with open(target, "wb") as fh:
        fh.write(new)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the map is stale, instead of rewriting it",
    )
    parser.add_argument("--quiet", action="store_true", help="say nothing")
    args = parser.parse_args()

    root = repo_root()
    paths = tracked_paths()
    text = render(paths, read_index(paths))

    if args.check:
        try:
            current = open(root / DOC_PATH, "rb").read()
        except FileNotFoundError:
            current = b""
        stale = current.replace(b"\r\n", b"\n") != text.encode("utf-8")
        if stale and not args.quiet:
            print(f"{DOC_PATH} is stale; run `uv run python scripts/doc_index.py`")
        return 1 if stale else 0

    if write(root, text) and not args.quiet:
        print(f"{DOC_PATH} rewritten")
    return 0


if __name__ == "__main__":
    sys.exit(main())
