"""The GUI: two panes, dispatching on types, never on tool identity.

Right pane generated by walking Params; left pane rendered from view
declarations, with overlays as editors bound to param fields -- drawing
a box and typing coordinates are the same mutation to the same param
(ARCHITECTURE.md "The GUI", "Building a pipeline"; DESIGN-SESSION.md
Exchange 2). The milestone reaches both panes plus the ROI overlay.
In-process-or-separate is not decided here (DEFERRED.md), and field-type
homes (the Rect-like ROI param type) are undesigned surface inside this
marker's scope.
"""

from sieve.debt import Owed

raise Owed(
    "20260802T023504Z: GUI two panes: Params-derived config pane, view-rendered canvas with"
    " ROI overlay bound to the param field; ARCHITECTURE.md 'The GUI',"
    " DESIGN-SESSION.md Exchange 2"
)
