"""Generate `.index.md` for the atomized documentation folders.

`docs/completed-todo/` and `docs/findings/` hold one file per item, each with
YAML frontmatter. A folder of thirty such files is unnavigable without a
summary, and a hand-maintained summary is a summary that is wrong — so the
index is derived, never edited, and `tests/docs/test_doc_index.py` fails when
it has drifted from the files it describes.

That is the same discipline `tests/bench/test_budget_table.py` applies to
`ARCHITECTURE.md`: prose that restates data is checked against the data.

    uv run nox -s docs            # rewrite both indexes
    python tools/doc_index.py --check   # exit 1 if either is stale
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Iterator, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, cast

import yaml

DOCS_ROOT = Path(__file__).resolve().parent.parent / "docs"

INDEX_NAME = ".index.md"
DELIMITER = "---"

#: Files whose names start with these are machinery, not entries: `_TEMPLATE.md`
#: and the generated index itself.
SKIP_PREFIXES = ("_", ".")

GENERATED_NOTICE = (
    "<!-- Generated by tools/doc_index.py. Do not edit; run `uv run nox -s docs`. -->"
)


class FrontmatterError(ValueError):
    """A file in an indexed folder could not be read as an entry."""


@dataclass(frozen=True, slots=True)
class ColumnSpec:
    """One table column, pulled from a frontmatter key."""

    header: str
    key: str
    #: Render the cell as a link to the entry. Exactly one column should.
    link: bool = False


@dataclass(frozen=True, slots=True)
class IndexSpec:
    """How to index one folder."""

    directory: str
    heading: str
    blurb: str
    columns: tuple[ColumnSpec, ...]
    #: Frontmatter keys every entry must carry. Missing ones are an error
    #: rather than an empty cell — a blank `verdict` is a finding nobody can
    #: triage from the table, which defeats the table.
    required: tuple[str, ...]


SPECS: tuple[IndexSpec, ...] = (
    IndexSpec(
        directory="completed-todo",
        heading="Completed",
        blurb=(
            "One file per finished TODO item, newest first. Each records what moved, "
            "what was decided, and what was rejected along the way."
        ),
        columns=(
            ColumnSpec("Date", "date"),
            ColumnSpec("Item", "title", link=True),
            ColumnSpec("Commit", "commit"),
            ColumnSpec("Summary", "summary"),
        ),
        required=("title", "date", "commit", "summary"),
    ),
    IndexSpec(
        directory="findings",
        heading="Findings",
        blurb=(
            "One file per measurement that shaped a decision, newest first. "
            "`verdict` is the whole result — open the file for the method."
        ),
        columns=(
            ColumnSpec("Date", "date"),
            ColumnSpec("Finding", "title", link=True),
            ColumnSpec("Status", "status"),
            ColumnSpec("Verdict", "verdict"),
        ),
        required=("title", "date", "status", "verdict"),
    ),
)


@dataclass(frozen=True, slots=True)
class Entry:
    """One indexed file and its parsed frontmatter."""

    path: Path
    fields: dict[str, Any]

    @property
    def sort_key(self) -> tuple[str, str]:
        """Newest first, then by filename so equal dates stay stable."""
        return (str(self.fields.get("date", "")), self.path.name)


def parse_frontmatter(path: Path) -> dict[str, Any]:
    """Read the YAML block delimited by `---` at the top of `path`.

    Raises:
        FrontmatterError: if the block is absent, unparseable, or not a mapping.
    """
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or lines[0].strip() != DELIMITER:
        raise FrontmatterError(f"{path}: no frontmatter — the file must open with `---`")

    try:
        end = next(i for i, line in enumerate(lines[1:], start=1) if line.strip() == DELIMITER)
    except StopIteration:
        raise FrontmatterError(f"{path}: frontmatter is never closed with `---`") from None

    try:
        loaded: object = yaml.safe_load("\n".join(lines[1:end]))
    except yaml.YAMLError as error:
        raise FrontmatterError(f"{path}: frontmatter is not valid YAML — {error}") from error

    if loaded is None:
        return {}
    if not isinstance(loaded, dict):
        kind = type(loaded).__name__
        raise FrontmatterError(f"{path}: frontmatter must be a mapping, got {kind}")
    # `safe_load` is typed as returning `Any`, so the narrowed `dict` is still
    # `dict[Unknown, Unknown]`. Restating the element types is what keeps this
    # module inside the repo's no-ignores rule.
    mapping = cast(dict[Any, Any], loaded)
    return {str(key): value for key, value in mapping.items()}


def collect(directory: Path, required: Sequence[str]) -> list[Entry]:
    """Parse every entry file in `directory`, newest first."""
    entries: list[Entry] = []
    for path in sorted(directory.glob("*.md")):
        if path.name.startswith(SKIP_PREFIXES):
            continue
        fields = parse_frontmatter(path)
        missing = [key for key in required if key not in fields]
        if missing:
            raise FrontmatterError(f"{path}: frontmatter is missing {', '.join(missing)}")
        entries.append(Entry(path=path, fields=fields))
    return sorted(entries, key=lambda entry: entry.sort_key, reverse=True)


def _cell(value: object) -> str:
    """Flatten a frontmatter value into one table cell.

    Newlines and pipes both break a markdown table, and YAML folded scalars
    (`summary: >`) routinely contain the former. Collapsing rather than
    truncating keeps the cell honest: an over-long summary is a signal the
    summary is doing too much, not something to hide.
    """
    if value is None:
        return ""
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, (list, tuple)):
        items = cast(Sequence[Any], value)
        parts = [_cell(item) for item in items]
        return ", ".join(part for part in parts if part)
    return " ".join(str(value).split()).replace("|", "\\|")


def render(spec: IndexSpec, entries: Sequence[Entry]) -> str:
    """Build the full text of one `.index.md`."""
    lines = [
        GENERATED_NOTICE,
        "",
        f"# {spec.heading}",
        "",
        spec.blurb,
        "",
    ]

    if not entries:
        lines.append("*No entries yet. Copy `_TEMPLATE.md` to `YYYY.MM.DD-short-name.md`.*")
        return "\n".join(lines) + "\n"

    lines.append("| " + " | ".join(column.header for column in spec.columns) + " |")
    lines.append("|" + "|".join("---" for _ in spec.columns) + "|")

    for entry in entries:
        cells: list[str] = []
        for column in spec.columns:
            text = _cell(entry.fields.get(column.key))
            if column.link:
                text = f"[{text or entry.path.stem}]({entry.path.name})"
            cells.append(text)
        lines.append("| " + " | ".join(cells) + " |")

    plural = "entry" if len(entries) == 1 else "entries"
    lines += ["", f"*{len(entries)} {plural}.*"]
    return "\n".join(lines) + "\n"


def build(root: Path = DOCS_ROOT) -> Iterator[tuple[Path, str]]:
    """Yield `(index path, desired content)` for every configured folder."""
    for spec in SPECS:
        directory = root / spec.directory
        if not directory.is_dir():
            raise FrontmatterError(f"{directory}: indexed folder does not exist")
        yield directory / INDEX_NAME, render(spec, collect(directory, spec.required))


def main(argv: Sequence[str] | None = None) -> int:
    """Write both indexes, or check them and report staleness."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if any index differs from what would be written",
    )
    args = parser.parse_args(argv)

    try:
        targets = list(build())
    except FrontmatterError as error:
        print(f"doc_index: {error}", file=sys.stderr)
        return 1

    stale: list[Path] = []
    for path, content in targets:
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if args.check:
            stale.append(path)
        else:
            path.write_text(content, encoding="utf-8")
            print(f"doc_index: wrote {path.relative_to(DOCS_ROOT.parent)}")

    if stale:
        listed = ", ".join(str(path.relative_to(DOCS_ROOT.parent)) for path in stale)
        print(f"doc_index: stale ({listed}) — run `uv run nox -s docs`", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
