"""Generate `.index.md` for the atomized documentation folders, plus
`docs/.state.md`, the one-read session primer.

`docs/completed-todo/` and `docs/findings/` hold one file per item, each with
YAML frontmatter. A folder of thirty such files is unnavigable without a
summary, and a hand-maintained summary is a summary that is wrong — so the
index is derived, never edited, and `tests/docs/test_doc_index.py` fails when
it has drifted from the files it describes.

The primer exists because transcript mining put ~11% of active session time
into re-orientation (see `findings/2026.07.27-session-time-is-generation-not-
tools.md`): it condenses what TODO.md, `todo/`, and the two indexes would
each be opened for at session start into one generated read. It deliberately
holds nothing unique — every line is derived, so it can never be the home of
a fact.

That is the same discipline `tests/bench/test_budget_table.py` applies to
`ARCHITECTURE.md`: prose that restates data is checked against the data.

    uv run nox -s docs            # rewrite both indexes
    python tools/doc_index.py --check   # exit 1 if either is stale
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Iterator, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, cast

import yaml

DOCS_ROOT = Path(__file__).resolve().parent.parent / "docs"

INDEX_NAME = ".index.md"
DELIMITER = "---"

#: Files whose names start with these are machinery, not entries: `_TEMPLATE.md`
#: and the generated index itself.
SKIP_PREFIXES = ("_", ".")

GENERATED_NOTICE = (
    "<!-- Generated by tools/doc_index.py. Do not edit; run `uv run nox -s docs`. -->"
)


class FrontmatterError(ValueError):
    """A file in an indexed folder could not be read as an entry."""


@dataclass(frozen=True, slots=True)
class ColumnSpec:
    """One table column, pulled from a frontmatter key."""

    header: str
    key: str
    #: Render the cell as a link to the entry. Exactly one column should.
    link: bool = False


@dataclass(frozen=True, slots=True)
class IndexSpec:
    """How to index one folder."""

    directory: str
    heading: str
    blurb: str
    columns: tuple[ColumnSpec, ...]
    #: Frontmatter keys every entry must carry. Missing ones are an error
    #: rather than an empty cell — a blank `verdict` is a finding nobody can
    #: triage from the table, which defeats the table.
    required: tuple[str, ...]


SPECS: tuple[IndexSpec, ...] = (
    IndexSpec(
        directory="completed-todo",
        heading="Completed",
        blurb=(
            "One file per finished TODO item, newest first. Each records what moved, "
            "what was decided, and what was rejected along the way."
        ),
        columns=(
            ColumnSpec("Date", "date"),
            ColumnSpec("Item", "title", link=True),
            ColumnSpec("Commit", "commit"),
            ColumnSpec("Summary", "summary"),
        ),
        required=("title", "date", "commit", "summary"),
    ),
    IndexSpec(
        directory="findings",
        heading="Findings",
        blurb=(
            "One file per measurement that shaped a decision, newest first. "
            "`verdict` is the whole result — open the file for the method."
        ),
        columns=(
            ColumnSpec("Date", "date"),
            ColumnSpec("Finding", "title", link=True),
            ColumnSpec("Status", "status"),
            ColumnSpec("Verdict", "verdict"),
        ),
        required=("title", "date", "status", "verdict"),
    ),
    IndexSpec(
        directory="todo",
        heading="Open and deferred work",
        blurb=(
            "One file per item. `status: open` is takeable now; `status: deferred` "
            "waits on the trigger in `gated_on`. Completion is a move to "
            "`completed-todo/` via `tools/complete_item.py`; promotion is a "
            "one-line `status:` edit."
        ),
        columns=(
            ColumnSpec("Status", "status"),
            ColumnSpec("Item", "title", link=True),
            ColumnSpec("Gated on", "gated_on"),
        ),
        required=("title", "status", "gated_on"),
    ),
)


@dataclass(frozen=True, slots=True)
class Entry:
    """One indexed file and its parsed frontmatter."""

    path: Path
    fields: dict[str, Any]

    @property
    def sort_key(self) -> tuple[str, str]:
        """Newest first, then by filename so equal dates stay stable."""
        return (str(self.fields.get("date", "")), self.path.name)


def parse_frontmatter(path: Path) -> dict[str, Any]:
    """Read the YAML block delimited by `---` at the top of `path`.

    Raises:
        FrontmatterError: if the block is absent, unparseable, or not a mapping.
    """
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or lines[0].strip() != DELIMITER:
        raise FrontmatterError(f"{path}: no frontmatter — the file must open with `---`")

    try:
        end = next(i for i, line in enumerate(lines[1:], start=1) if line.strip() == DELIMITER)
    except StopIteration:
        raise FrontmatterError(f"{path}: frontmatter is never closed with `---`") from None

    try:
        loaded: object = yaml.safe_load("\n".join(lines[1:end]))
    except yaml.YAMLError as error:
        raise FrontmatterError(f"{path}: frontmatter is not valid YAML — {error}") from error

    if loaded is None:
        return {}
    if not isinstance(loaded, dict):
        kind = type(loaded).__name__
        raise FrontmatterError(f"{path}: frontmatter must be a mapping, got {kind}")
    # `safe_load` is typed as returning `Any`, so the narrowed `dict` is still
    # `dict[Unknown, Unknown]`. Restating the element types is what keeps this
    # module inside the repo's no-ignores rule.
    mapping = cast(dict[Any, Any], loaded)
    return {str(key): value for key, value in mapping.items()}


def collect(directory: Path, required: Sequence[str]) -> list[Entry]:
    """Parse every entry file in `directory`, newest first."""
    entries: list[Entry] = []
    for path in sorted(directory.glob("*.md")):
        if path.name.startswith(SKIP_PREFIXES):
            continue
        fields = parse_frontmatter(path)
        missing = [key for key in required if key not in fields]
        if missing:
            raise FrontmatterError(f"{path}: frontmatter is missing {', '.join(missing)}")
        entries.append(Entry(path=path, fields=fields))
    return sorted(entries, key=lambda entry: entry.sort_key, reverse=True)


def _cell(value: object) -> str:
    """Flatten a frontmatter value into one table cell.

    Newlines and pipes both break a markdown table, and YAML folded scalars
    (`summary: >`) routinely contain the former. Collapsing rather than
    truncating keeps the cell honest: an over-long summary is a signal the
    summary is doing too much, not something to hide.
    """
    if value is None:
        return ""
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, list | tuple):
        items = cast(Sequence[Any], value)
        parts = [_cell(item) for item in items]
        return ", ".join(part for part in parts if part)
    return " ".join(str(value).split()).replace("|", "\\|")


def render(spec: IndexSpec, entries: Sequence[Entry]) -> str:
    """Build the full text of one `.index.md`."""
    lines = [
        GENERATED_NOTICE,
        "",
        f"# {spec.heading}",
        "",
        spec.blurb,
        "",
    ]

    if not entries:
        lines.append("*No entries yet. Copy `_TEMPLATE.md` to `YYYY.MM.DD-short-name.md`.*")
        return "\n".join(lines) + "\n"

    lines.append("| " + " | ".join(column.header for column in spec.columns) + " |")
    lines.append("|" + "|".join("---" for _ in spec.columns) + "|")

    for entry in entries:
        cells: list[str] = []
        for column in spec.columns:
            text = _cell(entry.fields.get(column.key))
            if column.link:
                text = f"[{text or entry.path.stem}]({entry.path.name})"
            cells.append(text)
        lines.append("| " + " | ".join(cells) + " |")

    plural = "entry" if len(entries) == 1 else "entries"
    lines += ["", f"*{len(entries)} {plural}.*"]
    return "\n".join(lines) + "\n"


STATE_NAME = ".state.md"

#: The long-view capabilities in `docs/ASPIRATIONS.md`, by id and title. An item
#: may name one or more in its optional `serves:` frontmatter key.
#:
#: The primer renders every aspiration, **including the ones nothing is
#: serving** — that visibility is the entire mechanism. Prior attempts to keep
#: the long view in front of a session put it in a document a session had to
#: choose to open, and inference chose not to. This routes it through the one
#: file the work loop already forces every session through.
#:
#: Deliberately not a gate: a test that failed when an aspiration had no open
#: item would manufacture busywork and teach people to tag falsely. The
#: reasoning is recorded in `ASPIRATIONS.md` under *How this stays in front of
#: a session*, which is the place to argue with it.
ASPIRATIONS: tuple[tuple[str, str], ...] = (
    ("A1", "A laggy session decomposes from its log"),
    ("A2", "SIEVE divides an unknown machine, and can say why"),
    ("A3", "SIEVE navigates the parameter space itself"),
)


def served_ids(entry: Entry) -> set[str]:
    """Aspiration ids an item declares in `serves:`.

    Accepts a bare string as well as a list, because `serves: A1` is what a
    hand-written frontmatter block tends to contain and rejecting it would be
    pedantry over a key that is optional in the first place.
    """
    raw: object = entry.fields.get("serves")
    if raw is None:
        return set()
    if isinstance(raw, str):
        return {raw.strip()}
    if isinstance(raw, list | tuple):
        return {str(item).strip() for item in cast(Sequence[Any], raw)}
    return {str(raw).strip()}


def aspiration_lines(items: Sequence[Entry]) -> list[str]:
    """The primer's aspiration block: each capability and what serves it."""
    lines = [
        "**Aspirations** — the long view (`ASPIRATIONS.md`), and what is walking",
        "toward it. An aspiration with nothing under it is the point of this block:",
        "",
    ]
    for key, title in ASPIRATIONS:
        serving = [entry for entry in items if key in served_ids(entry)]
        # Open items first: a session picking work should see takeable items
        # before it sees the deferred ones it cannot act on.
        serving.sort(key=lambda entry: (entry.fields.get("status") != "open", entry.path.name))
        lines.append(f"- **{key} — {title}**")
        if not serving:
            lines.append("  - *nothing is serving this*")
            continue
        for entry in serving:
            status = _cell(entry.fields.get("status"))
            name = _cell(entry.fields.get("title"))
            lines.append(f"  - [{name}](todo/{entry.path.name}) — {status}")
    return lines


def bug_bullets(todo_lines: Sequence[str]) -> list[str]:
    """Bullet lines of TODO.md's `## Bugs and tweaks` section."""
    bullets: list[str] = []
    inside = False
    for line in todo_lines:
        if line.startswith("## Bugs and tweaks"):
            inside = True
        elif inside and line.startswith("#"):
            break
        elif inside and line.startswith("- "):
            bullets.append(line)
    return bullets


def render_state(root: Path = DOCS_ROOT) -> str:
    """Build `docs/.state.md` from the item folder, TODO.md, and the indexes."""
    todo_md = (root / "TODO.md").read_text(encoding="utf-8").splitlines()
    bugs = bug_bullets(todo_md)

    by_dir = {spec.directory: spec for spec in SPECS}
    items = collect(root / "todo", by_dir["todo"].required)
    open_items = [e for e in items if e.fields.get("status") == "open"]
    deferred = [e for e in items if e.fields.get("status") == "deferred"]
    completed = collect(root / "completed-todo", by_dir["completed-todo"].required)
    findings = collect(root / "findings", by_dir["findings"].required)

    lines = [
        GENERATED_NOTICE,
        "",
        "# Repo state — the one-read session primer",
        "",
        "Every line here is derived; nothing is unique to this file. It exists",
        "so a session orients in one read instead of four.",
        "",
        f"**Open items ({len(open_items)})** — one file each in `todo/`:",
        "",
    ]
    for entry in open_items:
        gate = _cell(entry.fields.get("gated_on"))
        lines.append(f"- [{_cell(entry.fields.get('title'))}](todo/{entry.path.name}) — {gate}")
    lines += ["", f"**Deferred ({len(deferred)})** — the trigger is the whole line:", ""]
    for entry in deferred:
        gate = _cell(entry.fields.get("gated_on"))
        lines.append(f"- [{_cell(entry.fields.get('title'))}](todo/{entry.path.name}) — {gate}")

    lines += ["", *aspiration_lines(items)]

    lines += ["", f"**Bugs and tweaks queued in `TODO.md`:** {len(bugs)}"]
    lines += [
        "",
        "**Last completed** (full list in `completed-todo/.index.md`):",
        "",
    ]
    for entry in completed[:3]:
        lines.append(f"- {_cell(entry.fields.get('date'))} — {_cell(entry.fields.get('title'))}")
    lines += ["", "**Latest finding:**", ""]
    for entry in findings[:1]:
        lines.append(f"- {_cell(entry.fields.get('title'))} — {_cell(entry.fields.get('verdict'))}")
    return "\n".join(lines) + "\n"


def build(root: Path = DOCS_ROOT) -> Iterator[tuple[Path, str]]:
    """Yield `(path, desired content)` for every generated doc."""
    for spec in SPECS:
        directory = root / spec.directory
        if not directory.is_dir():
            raise FrontmatterError(f"{directory}: indexed folder does not exist")
        yield directory / INDEX_NAME, render(spec, collect(directory, spec.required))
    yield root / STATE_NAME, render_state(root)


def main(argv: Sequence[str] | None = None) -> int:
    """Write both indexes, or check them and report staleness."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if any index differs from what would be written",
    )
    args = parser.parse_args(argv)

    try:
        targets = list(build())
    except FrontmatterError as error:
        print(f"doc_index: {error}", file=sys.stderr)
        return 1

    stale: list[Path] = []
    for path, content in targets:
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if args.check:
            stale.append(path)
        else:
            path.write_text(content, encoding="utf-8")
            print(f"doc_index: wrote {path.relative_to(DOCS_ROOT.parent)}")

    if stale:
        listed = ", ".join(str(path.relative_to(DOCS_ROOT.parent)) for path in stale)
        print(f"doc_index: stale ({listed}) — run `uv run nox -s docs`", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
