"""Generate `.index.md` for the atomized documentation folders, plus
`docs/SETTLED.md` and `docs/.state.md`, the one-read session primer.

`docs/completed-todo/` and `docs/findings/` hold one file per item, each with
YAML frontmatter. A folder of thirty such files is unnavigable without a
summary, and a hand-maintained summary is a summary that is wrong — so the
index is derived, never edited, and `tests/docs/test_doc_index.py` fails when
it has drifted from the files it describes.

The primer exists because transcript mining put ~11% of active session time
into re-orientation (see `findings/2026.07.27-session-time-is-generation-not-
tools.md`): it condenses what `todo/` and the indexes would each be opened for
at session start into one generated read. It deliberately holds nothing unique
— every line is derived, so it can never be the home of a fact.

`SETTLED.md` is the same discipline applied to the anti-rediscovery table that
used to live in a hand-written `TODO.md`. Its rows are `settled:` blocks on
completed entries, so a row is written in the same file, at the same moment,
by the same tool as the entry that decided it.

That is the same discipline `tests/bench/test_budget_table.py` applies to
`ARCHITECTURE.md`: prose that restates data is checked against the data.

    uv run nox -s docs            # rewrite both indexes
    python tools/doc_index.py --check   # exit 1 if either is stale
"""

from __future__ import annotations

import argparse
import re
import sys
from collections.abc import Iterable, Iterator, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, cast

import yaml

DOCS_ROOT = Path(__file__).resolve().parent.parent / "docs"

INDEX_NAME = ".index.md"
DELIMITER = "---"

#: Files whose names start with these are machinery, not entries: `_TEMPLATE.md`
#: and the generated index itself.
SKIP_PREFIXES = ("_", ".")

GENERATED_NOTICE = (
    "<!-- Generated by tools/doc_index.py. Do not edit; run `uv run nox -s docs`. -->"
)


class FrontmatterError(ValueError):
    """A file in an indexed folder could not be read as an entry."""


@dataclass(frozen=True, slots=True)
class ColumnSpec:
    """One table column, pulled from a frontmatter key."""

    header: str
    key: str
    #: Render the cell as a link to the entry. Exactly one column should.
    link: bool = False


@dataclass(frozen=True, slots=True)
class IndexSpec:
    """How to index one folder."""

    directory: str
    heading: str
    blurb: str
    columns: tuple[ColumnSpec, ...]
    #: Frontmatter keys every entry must carry. Missing ones are an error
    #: rather than an empty cell — a blank `verdict` is a finding nobody can
    #: triage from the table, which defeats the table.
    required: tuple[str, ...]
    #: Order rows by `priority` instead of by date. Only `todo/` sets it:
    #: its entries carry no `date`, so the default sort is filename order,
    #: which is the one ordering that means nothing to a reader choosing work.
    by_priority: bool = False


SPECS: tuple[IndexSpec, ...] = (
    IndexSpec(
        directory="completed-todo",
        heading="Completed",
        blurb=(
            "One file per finished TODO item, newest first. The summary is the entry — "
            "a body is written only when a rejected alternative would otherwise be "
            "re-proposed."
        ),
        columns=(
            ColumnSpec("Date", "date"),
            ColumnSpec("Item", "title", link=True),
            ColumnSpec("Commit", "commit"),
            ColumnSpec("Summary", "summary"),
        ),
        # `none` is legal because optional is how the hand-written table this
        # replaces died: 20 -> 26 rows in one afternoon, then twelve commits
        # of building without gaining one.
        required=("title", "date", "commit", "summary", "settled"),
    ),
    IndexSpec(
        directory="findings",
        heading="Findings",
        blurb=(
            "One file per measurement that shaped a decision, newest first. "
            "`verdict` is the whole result — open the file for the method."
        ),
        columns=(
            ColumnSpec("Date", "date"),
            ColumnSpec("Finding", "title", link=True),
            ColumnSpec("Status", "status"),
            ColumnSpec("Verdict", "verdict"),
        ),
        required=("title", "date", "status", "verdict"),
    ),
    IndexSpec(
        directory="todo",
        heading="Open and deferred work",
        blurb=(
            "One file per item, most urgent first. `status: open` is takeable now; "
            "`status: deferred` waits on the trigger in `gated_on`. `priority` is "
            "how much it matters, independent of when it can be taken — "
            "`unassessed` means nobody has ranked it. Completion is a move to "
            "`completed-todo/` via `tools/complete_item.py`; promotion is a "
            "one-line `status:` edit."
        ),
        columns=(
            ColumnSpec("Priority", "priority"),
            ColumnSpec("Status", "status"),
            ColumnSpec("Item", "title", link=True),
            ColumnSpec("Gated on", "gated_on"),
        ),
        required=("title", "status", "gated_on", "priority"),
        by_priority=True,
    ),
)

#: Item priority, most urgent first — the order rows sort in, so the tuple is
#: the ranking and not merely the vocabulary.
#:
#: `unassessed` is a real value, and it is why the key is *required* rather
#: than optional. An absent key is invisible: the reader of the table cannot
#: tell an item nobody has ranked from one that is genuinely ordinary, and the
#: author editing the file never sees the question. Spelled out, it sorts last
#: and says what it is — the same trade `bench/budgets.py` makes with
#: `WITHOUT_PRODUCER` and `doc_drift` makes by listing an unstamped doc as
#: unassessable.
PRIORITIES: tuple[str, ...] = ("high", "normal", "low", "unassessed")

#: Item status, in the order rows sort: takeable, then waiting on a trigger,
#: then folded into other items. `superseded` exists because the other two
#: moves both lie about an absorbed item: completing it puts unfinished work
#: in the Completed index (rule 6's failure arriving through the docs), and
#: deferring it says timing was the decision when the decision was scope. A
#: superseded item keeps its file — inbound references, including ones in
#: `src/`, keep resolving — and names where its scope went in `superseded_by`.
STATUSES: tuple[str, ...] = ("open", "deferred", "superseded")


@dataclass(frozen=True, slots=True)
class Entry:
    """One indexed file and its parsed frontmatter."""

    path: Path
    fields: dict[str, Any]

    @property
    def sort_key(self) -> tuple[str, str]:
        """Newest first, then by filename so equal dates stay stable."""
        return (str(self.fields.get("date", "")), self.path.name)

    @property
    def priority_rank(self) -> int:
        """Position in `PRIORITIES`; anything unrecognised sorts last.

        Unrecognised cannot reach the generated docs — `test_todo_hygiene`
        fails the gate on a value outside the vocabulary — so the fallback is
        for the window between writing a typo and running the suite, where
        sorting it beside `high` would be the worse guess.
        """
        value = str(self.fields.get("priority", "")).strip()
        return PRIORITIES.index(value) if value in PRIORITIES else len(PRIORITIES)

    @property
    def status_rank(self) -> int:
        """Position in `STATUSES`; anything unrecognised sorts last, as with
        `priority_rank` and for the same window-between-typo-and-suite reason.
        """
        value = str(self.fields.get("status", "")).strip()
        return STATUSES.index(value) if value in STATUSES else len(STATUSES)


def item_order(entries: Iterable[Entry]) -> list[Entry]:
    """Most urgent first, takeable before waiting, then by filename.

    Named for the result rather than for the first key: status is a real part
    of the ordering, and a name that said only `priority` would leave the
    tiebreak discoverable solely by reading the body.

    Status breaks the tie because the index table interleaves the two — a
    reader scanning a band of equal priority wants the items they can act on
    at the top of it. The primer splits on status before it renders, so the
    tiebreak only ever moves rows in the table.
    """
    return sorted(
        entries,
        key=lambda entry: (
            entry.priority_rank,
            entry.status_rank,
            entry.path.name,
        ),
    )


def parse_frontmatter(path: Path) -> dict[str, Any]:
    """Read the YAML block delimited by `---` at the top of `path`.

    Raises:
        FrontmatterError: if the block is absent, unparseable, or not a mapping.
    """
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or lines[0].strip() != DELIMITER:
        raise FrontmatterError(f"{path}: no frontmatter — the file must open with `---`")

    try:
        end = next(i for i, line in enumerate(lines[1:], start=1) if line.strip() == DELIMITER)
    except StopIteration:
        raise FrontmatterError(f"{path}: frontmatter is never closed with `---`") from None

    try:
        loaded: object = yaml.safe_load("\n".join(lines[1:end]))
    except yaml.YAMLError as error:
        raise FrontmatterError(f"{path}: frontmatter is not valid YAML — {error}") from error

    if loaded is None:
        return {}
    if not isinstance(loaded, dict):
        kind = type(loaded).__name__
        raise FrontmatterError(f"{path}: frontmatter must be a mapping, got {kind}")
    # `safe_load` is typed as returning `Any`, so the narrowed `dict` is still
    # `dict[Unknown, Unknown]`. Restating the element types is what keeps this
    # module inside the repo's no-ignores rule.
    mapping = cast(dict[Any, Any], loaded)
    return {str(key): value for key, value in mapping.items()}


def collect(spec: IndexSpec, root: Path = DOCS_ROOT) -> list[Entry]:
    """Parse every entry file in `spec`'s folder, in that folder's order.

    Ordering happens here rather than at the call sites because the two
    consumers — the index table and the primer — must agree, and briefly did
    not: `by_priority` was declared on the spec, read by `build`, and
    re-applied by hand in `render_state`. Flipping the flag would have moved
    one and not the other. There is now no way to obtain entries in an order
    the spec did not declare.
    """
    directory = root / spec.directory
    if not directory.is_dir():
        raise FrontmatterError(f"{directory}: indexed folder does not exist")
    entries: list[Entry] = []
    for path in sorted(directory.glob("*.md")):
        if path.name.startswith(SKIP_PREFIXES):
            continue
        fields = parse_frontmatter(path)
        missing = [key for key in spec.required if key not in fields]
        if missing:
            raise FrontmatterError(f"{path}: frontmatter is missing {', '.join(missing)}")
        entries.append(Entry(path=path, fields=fields))
    if spec.by_priority:
        return item_order(entries)
    return sorted(entries, key=lambda entry: entry.sort_key, reverse=True)


def _cell(value: object) -> str:
    """Flatten a frontmatter value into one table cell.

    Newlines and pipes both break a markdown table, and YAML folded scalars
    (`summary: >`) routinely contain the former. Collapsing rather than
    truncating keeps the cell honest: an over-long summary is a signal the
    summary is doing too much, not something to hide.
    """
    if value is None:
        return ""
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, list | tuple):
        items = cast(Sequence[Any], value)
        parts = [_cell(item) for item in items]
        return ", ".join(part for part in parts if part)
    return " ".join(str(value).split()).replace("|", "\\|")


def render(spec: IndexSpec, entries: Sequence[Entry]) -> str:
    """Build the full text of one `.index.md`."""
    lines = [
        GENERATED_NOTICE,
        "",
        f"# {spec.heading}",
        "",
        spec.blurb,
        "",
    ]

    if not entries:
        lines.append("*No entries yet. Copy `_TEMPLATE.md` to `YYYY.MM.DD-short-name.md`.*")
        return "\n".join(lines) + "\n"

    lines.append("| " + " | ".join(column.header for column in spec.columns) + " |")
    lines.append("|" + "|".join("---" for _ in spec.columns) + "|")

    for entry in entries:
        cells: list[str] = []
        for column in spec.columns:
            text = _cell(entry.fields.get(column.key))
            if column.link:
                text = f"[{text or entry.path.stem}]({entry.path.name})"
            cells.append(text)
        lines.append("| " + " | ".join(cells) + " |")

    plural = "entry" if len(entries) == 1 else "entries"
    lines += ["", f"*{len(entries)} {plural}.*"]
    return "\n".join(lines) + "\n"


STATE_NAME = ".state.md"

#: The long-view capabilities in `docs/ASPIRATIONS.md`, by id and title. An item
#: may name one or more in its optional `serves:` frontmatter key.
#:
#: The primer renders every aspiration, **including the ones nothing is
#: serving** — that visibility is the entire mechanism. Prior attempts to keep
#: the long view in front of a session put it in a document a session had to
#: choose to open, and inference chose not to. This routes it through the one
#: file the work loop already forces every session through.
#:
#: Deliberately not a gate: a test that failed when an aspiration had no open
#: item would manufacture busywork and teach people to tag falsely. The
#: reasoning is recorded in `ASPIRATIONS.md` under *How this stays in front of
#: a session*, which is the place to argue with it.
ASPIRATIONS: tuple[tuple[str, str], ...] = (
    ("A1", "A laggy session decomposes from its log"),
    ("A2", "SIEVE divides an unknown machine, and can say why"),
    ("A3", "SIEVE navigates the parameter space itself"),
)


def served_ids(entry: Entry) -> set[str]:
    """Aspiration ids an item declares in `serves:`.

    Accepts a bare string as well as a list, because `serves: A1` is what a
    hand-written frontmatter block tends to contain and rejecting it would be
    pedantry over a key that is optional in the first place.
    """
    raw: object = entry.fields.get("serves")
    if raw is None:
        return set()
    if isinstance(raw, str):
        return {raw.strip()}
    if isinstance(raw, list | tuple):
        return {str(item).strip() for item in cast(Sequence[Any], raw)}
    return {str(raw).strip()}


#: `tools/complete_item.py` writes `completed-todo/YYYY.MM.DD-<slug>.md`, so a
#: slug survives completion and an edge pointing at an item never has to be
#: rewritten when that item finishes. That is the property the whole graph rests
#: on — it is what lets an edge show a *frontier* rather than a backlog.
DATE_PREFIX = re.compile(r"^\d{4}\.\d{2}\.\d{2}-")


def item_slug(entry: Entry) -> str:
    """The stable name of an item, in `todo/` or after the move to completed."""
    return DATE_PREFIX.sub("", entry.path.stem)


def after_slugs(entry: Entry) -> list[str]:
    """Slugs an item declares in `after:` — hard prerequisites that are items.

    Distinct from `gated_on`, which is a trigger and usually not an item at all
    (a measurement nobody has taken, a machine nobody owns). An `after:` list
    that has drained does not make an item takeable, it makes it *unblocked*;
    the trigger is still the gate. Bare strings are accepted for the same reason
    `serves:` accepts them.
    """
    raw: object = entry.fields.get("after")
    return _slug_list(raw)


def superseded_by_slugs(entry: Entry) -> list[str]:
    """Slugs a `status: superseded` item names as where its scope went.

    The same shape as `after:` and resolved against the same graph, because
    the failure is the same: a pointer written as prose survives a rename
    silently, a slug fails the suite.
    """
    raw: object = entry.fields.get("superseded_by")
    return _slug_list(raw)


def _slug_list(raw: object) -> list[str]:
    if raw is None:
        return []
    if isinstance(raw, str):
        return [raw.strip()] if raw.strip() else []
    if isinstance(raw, list | tuple):
        return [str(item).strip() for item in cast(Sequence[Any], raw) if str(item).strip()]
    return [str(raw).strip()]


@dataclass(frozen=True, slots=True)
class ItemGraph:
    """Every item in both directories, keyed by slug, with its `after:` edges."""

    #: slug -> entry, over `todo/` and `completed-todo/` together.
    nodes: dict[str, Entry]
    #: slug -> the slugs it declares in `after:`, verbatim and unresolved.
    edges: dict[str, list[str]]
    #: slugs that are complete, so an edge into one is satisfied.
    done: frozenset[str]

    def unresolved(self) -> list[tuple[str, str]]:
        """`(item, slug)` pairs where the slug names no file in either folder.

        An unresolved slug is a renamed item nobody updated — the failure this
        graph exists to make loud, since prose edges fail this way silently.
        """
        return [
            (slug, target)
            for slug, targets in sorted(self.edges.items())
            for target in targets
            if target not in self.nodes
        ]

    def cycles(self) -> list[list[str]]:
        """Every cycle reachable in the edge graph, as slug paths.

        A cycle is two items each claiming to come first. Today that would
        simply sit there looking like an ordering.
        """
        found: list[list[str]] = []
        seen: set[str] = set()

        def walk(slug: str, stack: list[str]) -> None:
            if slug in stack:
                found.append([*stack[stack.index(slug) :], slug])
                return
            if slug in seen or slug not in self.nodes:
                return
            seen.add(slug)
            for target in self.edges.get(slug, []):
                walk(target, [*stack, slug])

        for slug in sorted(self.nodes):
            walk(slug, [])
        return found

    def blockers(self, slug: str) -> list[str]:
        """Prerequisites of `slug` that are not complete."""
        return [t for t in self.edges.get(slug, []) if t not in self.done]


def build_graph(items: Sequence[Entry], completed: Sequence[Entry]) -> ItemGraph:
    """Index both folders by slug and read every `after:` edge."""
    nodes = {item_slug(entry): entry for entry in [*completed, *items]}
    edges = {item_slug(entry): after_slugs(entry) for entry in [*completed, *items]}
    return ItemGraph(
        nodes=nodes,
        edges={slug: targets for slug, targets in edges.items() if targets},
        done=frozenset(item_slug(entry) for entry in completed),
    )


def item_line(entry: Entry, tail: str = "") -> str:
    """One primer bullet: how urgent, which item, and optionally why not yet.

    Priority leads because the lists are sorted by it — a reader who stops
    after the first bullet has still read the most urgent item, which is the
    property a file-ordered list could not have.

    Every item bullet in the primer comes through here — the open list, the
    deferred list, and both halves of the frontier. They differ only in the
    tail, which is why three copies of the format was the wrong shape.
    """
    priority = _cell(entry.fields.get("priority"))
    title = _cell(entry.fields.get("title"))
    line = f"- **{priority}** — [{title}](todo/{entry.path.name})"
    return f"{line} — {tail}" if tail else line


def frontier_lines(open_items: Sequence[Entry], graph: ItemGraph) -> list[str]:
    """The primer's frontier: open items with no incomplete prerequisite.

    This is the one derived answer to *what can I take right now* — priority
    says what deserves taking, and this says what nothing else has to precede.
    Blocked items are shown with what blocks them rather than hidden, so the
    frontier is readable as a partition of the open list and not as a second,
    shorter list.
    """
    ranked = [(entry, graph.blockers(item_slug(entry))) for entry in open_items]
    ready = [entry for entry, blocked in ranked if not blocked]
    blocked = [(entry, blockers) for entry, blockers in ranked if blockers]

    lines = [
        f"**Frontier ({len(ready)} of {len(open_items)})** — open items whose `after:`",
        "prerequisites are all complete. `gated_on` is still the gate; this only says",
        "no *other item* has to come first:",
        "",
    ]
    lines += [item_line(entry) for entry in ready]
    if blocked:
        lines += ["", "Blocked on another item, with what blocks them:", ""]
        lines += [
            item_line(entry, ", ".join(f"`{slug}`" for slug in blockers))
            for entry, blockers in blocked
        ]
    return lines


def mermaid_lines(graph: ItemGraph) -> list[str]:
    """The item DAG, grouped into subgraphs by `serves:`.

    Only items carrying an edge are drawn. Thirty-four nodes render as a
    hairball and the unconnected ones carry no graph information — they are
    already listed above, in full. Cutting them is the item's own instruction
    for when the picture does not fit, applied to the axis that costs nothing.
    """
    drawn: set[str] = set()
    for slug, targets in graph.edges.items():
        drawn.add(slug)
        drawn.update(targets)
    drawn &= set(graph.nodes)
    if not drawn:
        return []

    def node_line(slug: str) -> str:
        entry = graph.nodes[slug]
        title = _cell(entry.fields.get("title")).replace('"', "'")
        mark = "✓ " if slug in graph.done else ""
        return f'    {slug.replace("-", "_")}["{mark}{title}"]'

    lines = [
        "**The item DAG** — `after:` edges only; an arrow points from a",
        "prerequisite to the item that waits on it. `✓` is complete. Items with no",
        "edge are omitted, not missing — they are the lists above.",
        "",
        "```mermaid",
        "graph LR",
    ]

    grouped: dict[str, list[str]] = {key: [] for key, _ in ASPIRATIONS}
    ungrouped: list[str] = []
    for slug in sorted(drawn):
        served = served_ids(graph.nodes[slug]) & set(grouped)
        if served:
            grouped[sorted(served)[0]].append(slug)
        else:
            ungrouped.append(slug)

    for key, title in ASPIRATIONS:
        if not grouped[key]:
            continue
        lines.append(f'  subgraph {key}["{key} — {title}"]')
        lines += [f"  {node_line(slug)}" for slug in grouped[key]]
        lines.append("  end")
    lines += [node_line(slug) for slug in ungrouped]

    for slug, targets in sorted(graph.edges.items()):
        for target in targets:
            if target in drawn:
                lines.append(f"    {target.replace('-', '_')} --> {slug.replace('-', '_')}")

    lines.append("```")
    return lines


def aspiration_lines(items: Sequence[Entry]) -> list[str]:
    """The primer's aspiration block: each capability and what serves it."""
    lines = [
        "**Aspirations** — the long view (`ASPIRATIONS.md`), and what is walking",
        "toward it. An aspiration with nothing under it is the point of this block:",
        "",
    ]
    for key, title in ASPIRATIONS:
        # Superseded items are excluded: their scope, and with it the
        # aspiration claim, lives in the successor named in `superseded_by`.
        serving = [
            entry
            for entry in items
            if key in served_ids(entry) and entry.fields.get("status") != "superseded"
        ]
        # Open items first: a session picking work should see takeable items
        # before it sees the deferred ones it cannot act on. Priority orders
        # within each half, for the same reason it orders the lists above.
        serving.sort(
            key=lambda entry: (
                entry.fields.get("status") != "open",
                entry.priority_rank,
                entry.path.name,
            )
        )
        lines.append(f"- **{key} — {title}**")
        if not serving:
            lines.append("  - *nothing is serving this*")
            continue
        for entry in serving:
            status = _cell(entry.fields.get("status"))
            name = _cell(entry.fields.get("title"))
            lines.append(f"  - [{name}](todo/{entry.path.name}) — {status}")
    return lines


SETTLED_NAME = "SETTLED.md"

#: `do_not_redecide` is the load-bearing one; the other two say where to look.
SETTLED_KEYS = ("what", "where", "do_not_redecide")

#: Written out rather than allowed to be absent, so the answer is a decision
#: somebody made and not a field somebody skipped.
SETTLED_NONE = "none"


def settled_rows(entry: Entry) -> list[dict[str, str]]:
    """The `settled:` rows of one completed entry, `[]` for `none`.

    Raises:
        FrontmatterError: on a shape that would render as a blank cell — the
            same reason `required` exists. A row missing `do_not_redecide` is
            the failure mode worth catching: it looks settled and says nothing.
    """
    raw: object = entry.fields.get("settled")
    if raw is None or (isinstance(raw, str) and raw.strip().lower() in {SETTLED_NONE, ""}):
        return []
    if not isinstance(raw, list):
        raise FrontmatterError(f"{entry.path}: `settled` must be a list of rows, or `none`")

    rows: list[dict[str, str]] = []
    for index, item in enumerate(cast(Sequence[Any], raw)):
        if not isinstance(item, dict):
            raise FrontmatterError(f"{entry.path}: `settled` row {index} is not a mapping")
        fields = {str(key): value for key, value in cast(dict[Any, Any], item).items()}
        missing = [key for key in SETTLED_KEYS if not str(fields.get(key, "")).strip()]
        if missing:
            raise FrontmatterError(
                f"{entry.path}: `settled` row {index} is missing {', '.join(missing)}"
            )
        rows.append({key: _cell(fields[key]) for key in SETTLED_KEYS})
    return rows


def overturns_list(entry: Entry) -> list[str]:
    """The `what` values of settled rows this completed entry re-decided.

    A settled row is law until the entry that re-decides it lands; editing the
    original entry to retract the row would edit a dated record, and leaving
    both standing would put two contradictory instructions in one table. So
    the overturning entry names the row, the row moves to the Overturned
    section with both pointers, and the original file is never touched. The
    match is on the row's `what` column, exact — a typo is a suite failure
    (`test_todo_hygiene`), not a row that quietly stays law.
    """
    raw: object = entry.fields.get("overturns")
    return _slug_list(raw)


def render_settled(completed: Sequence[Entry]) -> str:
    """Build `docs/SETTLED.md` — what a new item must not re-decide.

    Ordered by `where`, which sorts the layers into the order they stack
    (`bench`, `core`, `decode`, `filters`, `gui`, `pipeline`) for free. Date
    order was the alternative and is wrong here: a reader arrives with a
    module in hand, not a date.
    """
    overturned_by: dict[str, Entry] = {
        what: entry for entry in completed for what in overturns_list(entry)
    }
    all_rows = [(row, entry) for entry in completed for row in settled_rows(entry)]
    rows = [(row, entry) for row, entry in all_rows if row["what"] not in overturned_by]
    overturned = [(row, entry) for row, entry in all_rows if row["what"] in overturned_by]
    rows.sort(key=lambda pair: (pair[0]["where"].strip("`"), pair[0]["what"]))
    overturned.sort(key=lambda pair: (pair[0]["where"].strip("`"), pair[0]["what"]))

    lines = [
        GENERATED_NOTICE,
        "",
        "# What already exists — take it, do not rebuild it",
        "",
        "Every row is a `settled:` block in the `docs/completed-todo/` entry that",
        "decided it; that entry is the home and this table is derived. The third",
        "column is the part that costs a day if you re-derive it.",
        "",
        "| What | Where | What you must not re-decide | Settled by |",
        "|---|---|---|---|",
    ]
    for row, entry in rows:
        link = f"[{entry.fields.get('date')}](completed-todo/{entry.path.name})"
        lines.append(f"| {row['what']} | {row['where']} | {row['do_not_redecide']} | {link} |")

    if overturned:
        lines += [
            "",
            "## Overturned",
            "",
            "Rows a later entry re-decided. The original entry is a dated record",
            "and stands unedited; the row is no longer law, and the second link",
            "says what replaced it.",
            "",
            "| What | Was settled by | Overturned by |",
            "|---|---|---|",
        ]
        for row, entry in overturned:
            over = overturned_by[row["what"]]
            was = f"[{entry.fields.get('date')}](completed-todo/{entry.path.name})"
            now = f"[{over.fields.get('date')}](completed-todo/{over.path.name})"
            lines.append(f"| {row['what']} | {was} | {now} |")

    silent = sum(1 for entry in completed if not settled_rows(entry))
    lines += [
        "",
        f"*{len(rows)} rows from {len(completed) - silent} entries; "
        f"{silent} entries settled nothing"
        + (f"; {len(overturned)} rows overturned.*" if overturned else ".*"),
    ]
    return "\n".join(lines) + "\n"


def budget_health() -> str:
    """One line: the load-bearing gap in rule 4's table.

    In-pipeline is the regime the product is sold on, and untimed is the
    widest of the three gaps — published and in-debt are both visible from
    `budgets.py` itself and did not earn a line here. Derived, so it is safe
    in a file `--check` compares byte-for-byte; tree state and `doc_drift`'s
    worst line move with `HEAD` and went to the Stop hook and the `docs`
    report instead.
    """
    from sieve.bench.budgets import BUDGETS, TIMED

    pre_pipeline = {"open_to_first_frame", "scrub_settle"}
    in_pipeline = set(BUDGETS) - pre_pipeline
    return (
        f"**Budgets:** {len(in_pipeline - TIMED)} of {len(in_pipeline)} in-pipeline "
        f"budgets have no CI benchmark asserting a limit."
    )


def placement_health(root: Path = DOCS_ROOT) -> str | None:
    """One line: how much of the rework's exception list remains.

    REWORK.md's claim is that the exception list is the work list; a list
    nobody opens the file for is a list that grows, so its size is rendered
    into the one file every session reads. Derived from `.importlinter` by
    parse, so it is safe in a byte-exact `--check` — the same constraint
    `budget_health` documents. `None` once the contract is gone (graduated
    into ARCHITECTURE.md), which removes the line rather than rendering a
    zero for a ceiling that no longer exists.
    """
    import configparser

    path = root.parent / ".importlinter"
    if not path.is_file():
        # A fixture tree (`render_state(tmp_path)` in the tests) has no
        # contract file; that is a tree with no work list, not an error.
        return None
    parser = configparser.ConfigParser(interpolation=None)
    parser.read_string(path.read_text(encoding="utf-8"))
    section = "importlinter:contract:gui-computes-nothing"
    if not parser.has_section(section):
        return None
    raw = parser.get(section, "ignore_imports", fallback="")
    ignored = [line for line in raw.splitlines() if line.strip()]
    plural = "import" if len(ignored) == 1 else "imports"
    return (
        f"**Placement:** {len(ignored)} GUI {plural} of computation remain "
        f"(`gui-computes-nothing` in `.importlinter` — the rework's work list)."
    )


def trigger_health() -> str:
    """One line: AUTO-GUARDRAILS' armed triggers and how stale the oldest is.

    A trigger nobody re-reads is the §2 failure — it fired at schema v3 and
    stayed fired for a fortnight — so the count belongs in the file every
    session opens rather than in the one it opens when it remembers to.
    Deferred import: `guardrail_refs` reads this module through `doc_refs`.
    """
    from guardrail_refs import trigger_health as line

    return line()


def render_state(root: Path = DOCS_ROOT) -> str:
    """Build `docs/.state.md` from the item folder and the indexes."""
    by_dir = {spec.directory: spec for spec in SPECS}
    items = collect(by_dir["todo"], root)
    open_items = [e for e in items if e.fields.get("status") == "open"]
    deferred = [e for e in items if e.fields.get("status") == "deferred"]
    superseded = [e for e in items if e.fields.get("status") == "superseded"]
    completed = collect(by_dir["completed-todo"], root)
    findings = collect(by_dir["findings"], root)

    lines = [
        GENERATED_NOTICE,
        "",
        "# Repo state — the one-read session primer",
        "",
        "Every line here is derived; nothing is unique to this file. It exists",
        "so a session orients in one read instead of four.",
        "",
        f"**Open items ({len(open_items)})** — one file each in `todo/`, most urgent",
        "first. `unassessed` means nobody has ranked it, not that it ranked low:",
        "",
    ]
    lines += [item_line(e, _cell(e.fields.get("gated_on"))) for e in open_items]
    lines += ["", f"**Deferred ({len(deferred)})** — the trigger is the whole line:", ""]
    lines += [item_line(e, _cell(e.fields.get("gated_on"))) for e in deferred]
    if superseded:
        lines += [
            "",
            f"**Superseded ({len(superseded)})** — the scope moved; the tail says where.",
            "The file stays so references keep resolving; do not take these:",
            "",
        ]
        lines += [
            item_line(e, ", ".join(f"`{slug}`" for slug in superseded_by_slugs(e)))
            for e in superseded
        ]

    graph = build_graph(items, completed)
    lines += ["", *frontier_lines(open_items, graph)]
    lines += ["", *aspiration_lines(items)]
    mermaid = mermaid_lines(graph)
    if mermaid:
        lines += ["", *mermaid]

    lines += ["", budget_health()]
    placement = placement_health(root)
    if placement:
        lines += ["", placement]
    lines += ["", trigger_health()]
    lines += [
        "",
        "**Last completed** (full list in `completed-todo/.index.md`):",
        "",
    ]
    for entry in completed[:3]:
        lines.append(f"- {_cell(entry.fields.get('date'))} — {_cell(entry.fields.get('title'))}")
    lines += ["", "**Latest finding:**", ""]
    for entry in findings[:1]:
        lines.append(f"- {_cell(entry.fields.get('title'))} — {_cell(entry.fields.get('verdict'))}")
    return "\n".join(lines) + "\n"


def build(root: Path = DOCS_ROOT) -> Iterator[tuple[Path, str]]:
    """Yield `(path, desired content)` for every generated doc."""
    for spec in SPECS:
        yield root / spec.directory / INDEX_NAME, render(spec, collect(spec, root))
    completed_spec = next(spec for spec in SPECS if spec.directory == "completed-todo")
    completed = collect(completed_spec, root)
    yield root / SETTLED_NAME, render_settled(completed)
    yield root / STATE_NAME, render_state(root)


def main(argv: Sequence[str] | None = None) -> int:
    """Write both indexes, or check them and report staleness."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if any index differs from what would be written",
    )
    args = parser.parse_args(argv)

    try:
        targets = list(build())
    except FrontmatterError as error:
        print(f"doc_index: {error}", file=sys.stderr)
        return 1

    stale: list[Path] = []
    for path, content in targets:
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if args.check:
            stale.append(path)
        else:
            path.write_text(content, encoding="utf-8")
            print(f"doc_index: wrote {path.relative_to(DOCS_ROOT.parent)}")

    if stale:
        listed = ", ".join(str(path.relative_to(DOCS_ROOT.parent)) for path in stale)
        print(f"doc_index: stale ({listed}) — run `uv run nox -s docs`", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
