"""Pure logic. The bottom of the layer stack.

Nothing here imports from a layer above it, and nothing here imports Qt,
Zarr, or subprocess. That is machine-checked by the import contracts in
`.importlinter` rather than by review.
"""

from sieve.core.filter_base import (
    UNCHANGED_RATE,
    ArraySpec,
    CostEstimate,
    FilterSpec,
    Mode,
    ParamsBase,
    StreamKind,
    StreamSpec,
    TableSpec,
    source_warmup_frames,
)
from sieve.core.filter_registry import (
    REGISTRY,
    DuplicateFilterError,
    FilterRegistry,
    UnknownFilterError,
    register_filter,
)
from sieve.core.pipeline_model import (
    PROJECT_SUFFIX,
    SCHEMA_VERSION,
    ClipRange,
    DetectorSettings,
    Edge,
    Node,
    Pipeline,
    Project,
    Sink,
    SourceRef,
    as_project_path,
    project_path_for,
)
from sieve.core.replicates import Replicate, ReplicateSet
from sieve.core.types import (
    NO_FRAMES,
    ROI,
    ChannelSpec,
    Frame,
    FrameCount,
    FrameSpan,
    MediaTime,
    VideoMetadata,
    WallTime,
    WorkUnits,
)

__all__ = [
    "NO_FRAMES",
    "PROJECT_SUFFIX",
    "REGISTRY",
    "ROI",
    "SCHEMA_VERSION",
    "UNCHANGED_RATE",
    "ArraySpec",
    "ChannelSpec",
    "ClipRange",
    "CostEstimate",
    "DetectorSettings",
    "DuplicateFilterError",
    "Edge",
    "FilterRegistry",
    "FilterSpec",
    "Frame",
    "FrameCount",
    "FrameSpan",
    "MediaTime",
    "Mode",
    "Node",
    "ParamsBase",
    "Pipeline",
    "Project",
    "Replicate",
    "ReplicateSet",
    "Sink",
    "SourceRef",
    "StreamKind",
    "StreamSpec",
    "TableSpec",
    "UnknownFilterError",
    "VideoMetadata",
    "WallTime",
    "WorkUnits",
    "as_project_path",
    "project_path_for",
    "register_filter",
    "source_warmup_frames",
]
